---
title: "Trabajo1"
format: html
editor: visual
bibliography: Trabajo1.bib
link-citations: true 
---

# #Nivel Educativo y Movilidad Social

Para la sociedad moderna y la sociologia actual la movilidad social surge como una problematica social y politica escencial para comprender la realidad practica de los sujetos sociales respecto a sus condiciones de clase. La clase se constituye de un sin fin de variables sociales como los pueden ser, la cantidad de integrantes del hogar, el sexo, el genero, la edad, el ingreso del hogar, la educacion , etc. Todas estas variables pertecen a la composicion de la clase social las que pueden variar dependiendo de la sociedad que se encuentre estudiando .

Para esta investigacion nos centraremos en describir que es lo que esta ocurriendo con las clases sociales respecto a la capacidad de los individuos para poder ascender o descender entre las diferentes clases sociales, sin embargo las variables que puedan tener relacion con la movilidad son variadas como antes mencionado por lo que buscaremos establecer la relacion entre "Nivel educativo" y su influencia para la capacidad de poder ejercer la movilidad social, es decir haremos un analisis respecto a la capacidad agencial del nivel educativo para poder influir o no en la movilidad social. La movilidad social que se tratara en esta investugacion tendra una perspectiva de caracter intergeneracional, es decir que se hablara de movilidad social comparando la clase social a la que se pueda pertenecer entre generaciones para asi poder observar si la movilidad social es ascendete, descentende o si esta se mantiene a traves del tiempo.

La clase social es un concepto que puesto en el largo tiempo historico ha sido victima de distintas transformaciones como bien se señala en [@erzsébetbukodi2015] las cuales han presenciado el fenomeno de la movilidad social como bien se puede ver en [@eriksonHasSocialMobility2010] propias del paso del tiempo y por supuesto del tipo de sociedad en que nos encontremos. En la actualidad sin duda el concepto de clase es un atributo propio de cada uno de los individuos, ninguno de nosotros es ageno a dicho conepto, como consecuencia para la sociologia el problema de la movilidad social resulta ser de mucho interes, puesto que esta problematica permite identificar una realidad generalizada respecto a la situasion de clase en cada individuo. Segun Jhon Goldthrope [@johnh.goldthorpe2004] por lo que es relevante que para la sociologia y en particular en esta investigacion observemos diferentes variables como la "educacion" para poder observar la movilidad social.

En esta investigacion buscaremos reconocer y caracterizar la movilidad social, con el fin de identificar como es la movilidad social en la actualidad si es que la hay o no y que efectos pueda tener para la sociedad la presencia o ausencia de esta, asi mismo estableceremos la relevancia del nivel educativo como herramineta necesaria para poder ascender o descender entre las clases sociales dado la relevancia de esta variable segun [@erzsebetbukodiEducationalAttainmentRelative2016]

Como hipotesis de investigacion se ha planateado la siguiente afirmacion, la educacion como herramineta social para poder ascender o descender entre las clases sociales posee una relevancia sustancial entre los sectores medios y bajos.
